//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Unauthorizeed_exit = new HashSet<Unauthorizeed_exit>();
        }
    
        public int Pro_id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Weight { get; set; }
        public string PureWeight { get; set; }
        public string Karat { get; set; }
        public string ImageUrl { get; set; }
        public string Serial_number { get; set; }
        public int Calssification_Id { get; set; }
        public int Categorize_Id { get; set; }
        public string Imported_Quantity { get; set; }
        public int made { get; set; }
    
        public virtual Cateqorize Cateqorize { get; set; }
        public virtual Classification Classification { get; set; }
        public virtual Cuntry Cuntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unauthorizeed_exit> Unauthorizeed_exit { get; set; }
    }
}
