//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unauthorizeed_exit
    {
        public int Id { get; set; }
        public int Pro_id { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public int Door_num { get; set; }
        public int User_id { get; set; }
        public string Information { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
    }
}
